name: Train Model

on:
  push:
    branches:
      - main
    paths:
      - 'github-actions-mlops/**'
  pull_request:
    branches:
      - main
    paths:
      - 'github-actions-mlops/**'
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          
      - name: Install dependencies
        working-directory: ./github-actions-mlops
        run: python -m pip install -r requirements.txt
        
      - name: Train model
        working-directory: ./github-actions-mlops
        run: python train.py
        
      - name: Deploy to Hugging Face
        working-directory: ./github-actions-mlops
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
          HUGGINGFACE_REPO_ID: ${{ secrets.HUGGINGFACE_REPO_ID }}
        run: python deploy_hf.py
